{
 "openapi": "3.1.0",
 "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
 "info": {
  "title": "Airthings API",
  "version": "v1",
  "contact": {
   "name": "Airthings Support",
   "email": "support@airthings.com"
  }
 },
 "servers": [
  {
   "url": "https://ext-api.airthings.com"
  }
 ],
 "paths": {
  "/v1/accounts": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Accounts list",
    "description": "Get all accessible accounts",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device list",
    "description": "Get account devices",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Devices"
    ],
    "summary": "Update devices",
    "description": "Update names of the devices.",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device info",
    "description": "Get info about a specific device",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/battery": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device battery history",
    "description": "Get battery history of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/latest-battery": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device battery latest-values",
    "description": "Get latest battery info of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/latest-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples latest-values",
    "description": "Get latest samples of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history",
    "description": "Get samples of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/hourly-radon-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history - hourly radon",
    "description": "Get hourly radon samples of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/mold-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history - mold",
    "description": "Get mold samples history of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/virus-risk-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history - virus risk",
    "description": "Get virus risk samples history of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/occupancy-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history - occupancy",
    "description": "Get occupancy samples history of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/ventilation-samples": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device samples history - ventilation",
    "description": "Get ventilation samples history of a specific device from the latest measuring segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/{serialNumber}/threshold-breaches": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Device threshold notifications",
    "description": "Get threshold breaches for a given device. A threshold breach is generated every time one of\nthe device sensors reports a value that crosses a predefined threshold value",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/devices/labels": {
   "patch": {
    "tags": [
     "Devices"
    ],
    "summary": "Set device labels",
    "description": "Set labels on one or more devices, creating labels that do not exist and updating labels that do exist.\nLabels can only be set for devices that have an active segment. If the active segment for a device ends\n(becomes inactive), the labels set by this endpoint will be cleared, and labels will have to be set \nagain. This endpoint is idempotent provided that none of the devices operated on have their active segment\nchanged between requests.",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/segments": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment list",
    "description": "Get measurement segments belong to the account",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment info",
    "description": "Get information on a measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history",
    "description": "Get samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/mold-samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history - mold",
    "description": "Get mold samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/virus-risk-samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history - virus risk",
    "description": "Get virus risk samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/occupancy-samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history - Occupancy",
    "description": "Get occupancy samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/ventilation-samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history - Ventilation",
    "description": "Get ventilation samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/segments/{segmentId}/hourly-radon-samples": {
   "get": {
    "tags": [
     "Segments"
    ],
    "summary": "Segment samples history - Hourly Radon",
    "description": "Get hourly radon samples history of a specific measurement segment",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/locations": {
   "get": {
    "tags": [
     "Locations"
    ],
    "summary": "Location list",
    "description": "Get all locations",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device",
       "write:device"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Locations"
    ],
    "summary": "Add location",
    "description": "Add a new location to an organization",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device",
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/locations/{locationId}": {
   "get": {
    "tags": [
     "Locations"
    ],
    "summary": "Location info",
    "description": "Get info about a specific location",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/locations/{locationId}/latest-samples": {
   "get": {
    "tags": [
     "Locations"
    ],
    "summary": "Location latest samples",
    "description": "Get latest samples belonging to devices in a specific location (latest segment)",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "/v1/locations/{locationId}/devices": {
   "post": {
    "tags": [
     "Locations"
    ],
    "summary": "Add a device to a location",
    "description": "Add a new device to a location. The `serialNumber` and `id` can be found on the back of the device.\nNote that the `id` in this context is not the `serialNumber`, as it can be when requesting resources\nin other Airthings APIs. To use this endpoint, make sure your API client has the `write:device` scope\nenabled in the dashboard and that the `write:device` scope is added to your access token\nwhen requesting a token from the token endpoint.",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/webhooks": {
   "get": {
    "tags": [
     "Webhooks"
    ],
    "summary": "Webhook list",
    "description": "Get all added webhooks",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device",
       "write:device"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "Add Webhook",
    "description": "Add a new webhook",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device",
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/webhooks/{hookId}": {
   "delete": {
    "tags": [
     "Webhooks"
    ],
    "summary": "Delete Webhook",
    "description": "Delete a webhook",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Webhooks"
    ],
    "summary": "Edit Webhook",
    "description": "Edit a webhook in an organization. Only locations is supported at this time.\nValue type of this endpoint is currently a list of location IDs that you wish to\nperform the operation on.",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "write:device"
      ]
     }
    ]
   }
  },
  "/v1/organizations": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Organizations list",
    "description": "Get all available organizations",
    "deprecated": false,
    "security": [
     {
      "AirthingsAccounts": [
       "read:device"
      ]
     }
    ]
   }
  },
  "//v1/thresholds": {
   "get": {
    "tags": [
     "Thresholds"
    ],
    "summary": "Device thresholds",
    "description": "Get threshold values for a device's sensors",
    "deprecated": false,
    "security": []
   }
  }
 },
 "webhooks": {},
 "components": {
  "securitySchemes": {
   "AirthingsAccounts": {
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.airthings.com/authorize",
      "tokenUrl": "https://accounts-api.airthings.com/v1/token",
      "scopes": {
       "read:device": "Allowing a user to read data from devices in their account",
       "write:device": "Allowing a user to manage devices within their account"
      }
     },
     "clientCredentials": {
      "tokenUrl": "https://accounts-api.airthings.com/v1/token",
      "scopes": {
       "read:device": "Allowing a user to read data from devices in their account",
       "write:device": "Allowing a user to manage devices within their account"
      }
     }
    },
    "type": "oauth2"
   }
  }
 },
 "security": [
  {
   "AirthingsAccounts": []
  }
 ],
 "tags": [
  {
   "name": "Accounts"
  },
  {
   "name": "Devices"
  },
  {
   "name": "Locations"
  },
  {
   "name": "Organizations"
  },
  {
   "name": "Segments"
  },
  {
   "name": "Thresholds"
  },
  {
   "name": "Webhooks"
  }
 ]
}